### ISSUE TITLE
Migrate to http ^1.0.0 to fix build issues on flutter 3.13

### ISSUE THREAD

**Issue by petermusembi69** [slimpotatoboy/slack_logger#5]
I am having dependencies conflict bug, kindly consider migrating to http version ^1.0.0 from the current version http ^0.13.5. 

Adding a depandabot can assist in always keeping this package upto date 

```yaml
#file location ./github/dependabot.yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
```
